package io.pivotal.extremerstartup.question

val ENGLISH_WORD_LIST = listOf(
        "banana",
        "september",
        "cloud",
        "zoo",
        "ruby",
        "buzzword",
        "pivotal",
        "java",
        "truth",
        "beauty",
        "freedom",
        "love",
        "restaurant",
        "menu",
        "food",
        "parents",
        "dad",
        "west",
        "east",
        "twenty",
        "year",
        "clove",
        "cleave",
        "close",
        "choose",
        "rhythm",
        "euouae",
        "time",
        "foundry",
        "tracker",
        "green",
        "plum"
)